apiVersion: v1
appVersion: 24.1.2-1384
description: AppDynamics distributed Opentelemetry Collector Helm chart for Kubernetes
maintainers:
- email: support@appdynamics.com
  name: AppDynamics
name: appdynamics-otel-collector
version: 24.1.2-1384
