pack:
  # The namespace (on the target cluster) in which the pack will be deployed.
  # When the namespace is not found, a new namespace will be created with the name specified.
  namespace: "ngrok-ingress-controller"

  content:
    images:
      - image: docker.io/ngrok/kubernetes-ingress-controller:0.7.0

charts:  
  kubernetes-ingress-controller:
    ## @section Common parameters
    ##

    ## @param nameOverride String to partially override generated resource names
    ## @param fullnameOverride String to fully override generated resource names
    ## @param commonLabels Labels to add to all deployed objects
    ## @param commonAnnotations Annotations to add to all deployed objects
    ##
    nameOverride: ""
    fullnameOverride: "ngrok-ingress-controller"
    commonLabels: {}
    commonAnnotations: {}

    ## @section Controller parameters
    ##

    ## @param podAnnotations Used to apply custom annotations to the ingress pods.
    ## @param podLabels Used to apply custom labels to the ingress pods.
    ##
    podAnnotations: {}
    podLabels: {}

    ## @param replicaCount The number of controllers to run.
    ## A minimum of 2 is recommended in production for HA.
    ##
    replicaCount: 2
