
name: Push Packs

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      registry:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Push packs to registry'
        # Default value if no value is explicitly provided
        default: 'stage'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  push-packs:
    env: stage
    runs-on: ubuntu-latest

    steps:
    - name: Display registry
      run: echo "Hello ${{ github.event.inputs.registry }}"

    - name: Checkout branch
      uses: actions/checkout@main

    - name: Push to Dev
      if: ${{ inputs.registry == 'dev' }}
      run: |
        cd ${GITHUB_WORKSPACE}/scripts
        ./push_packs.sh ${{ secrets.DEV_REGISTRY_SERVER }} ${{ secrets.DEV_REGISTRY_CREDS }}

    - name: Push to Stage
      if: ${{ inputs.registry == 'stage' }}
      run: |
        cd ${GITHUB_WORKSPACE}/scripts
        ./push_packs.sh ${{ secrets.STAGE_REGISTRY_SERVER }} ${{ secrets.STAGE_REGISTRY_CREDS }}

    - name: Push to Prod
      if: ${{ inputs.registry == 'prod' }}
      run: |
        cd ${GITHUB_WORKSPACE}/scripts
        ./push_packs.sh ${{ secrets.PROD_REGISTRY_SERVER }} ${{ secrets.PROD_REGISTRY_CREDS }}
